### ISSUE TITLE
k8s 使用 Pod 来部署应用

### ISSUE THREAD

**Issue by lqshow** [lqshow/notes#38]
Pod 是 k8s 进行资源调度的最小部署单位，里面包含了很多的 container，实际上每一个 container  对应一个应用实例。我们先来看下如何通过 k8s 来部署一个 container。

### 1. 创建 Pod
Pod 的 yaml 定义如下
```yaml
apiVersion: v1
kind: Pod

metadata:
  name: nginx-po
  labels:
    app: nginx
    
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```
执行命令生成 Pod
```bash
kubectl create -f nginx-pod.yml
```

看下 Pod 的信息

```bash
➜  lab1 kubectl get po -o wide -l app=nginx
NAME       READY     STATUS    RESTARTS   AGE       IP          NODE
nginx-po   1/1       Running   0          5m        10.1.0.69   docker-for-desktop
```

### 2. 创建 Service

以上 pod 定义的 yaml 是不能直接访问 pod 内的网络的，访问 Pod 需要通过 Service 来实现。

我们知道每个 Pod 都有一个自己的 IP 地址，当 Pod 发生故障后，新的 Pod 会分配到一个新的 IP 地址。Service 是通过 label 来维护 Pod 的映射关系，完全不需要关心 Pod的 IP 地址，正如下面Service spec的定义，通过 selector 来筛选 Pod

Service 的 yaml 定义如下

```yaml
apiVersion: v1
kind: Service

metadata:
  name: nginx-svc
  labels:
    app: nginx

spec:
  ports:
  - port: 3000
    name: http
    targetPort: 80
    protocol: TCP

  selector:
    app: nginx
    
  type: NodePort
```

执行命令生成 Service

```bash
kubectl create -f nginx-svc.yml
```

看下 Service 的信息

```bash
➜  lab1 kubectl get svc -o wide -l app=nginx
NAME        TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE       SELECTOR
nginx-svc   NodePort   10.101.115.134   <none>        3000:31876/TCP   29s       app=nginx
```

通过访问localhsot 的31876端口能看到 nginx 的页面

![image](https://user-images.githubusercontent.com/8086910/44615442-ebc09000-a86c-11e8-9ba2-72d876f6d2af.png)

#### Service Port的说明

| Port       | Desc                                    |
| ---------- | --------------------------------------- |
| port       | service暴露在cluster ip上的端口（3000） |
| targetPort | pod上的端口（80）                       |
| nodePort   | 节点端口（31876）                       |

port 和 nodePort 都是 Service 上的端口

port 暴露给集群内客户访问服务（<cluster Ip>:port）

nodePort 暴露给集群外客户访问服务（<node Ip>:nodePort）

从这两个端口到来的数据都需要经过反向代理 kube-proxy 流入后端 pod 的 targetPod，从而到达 pod 上的容器内。
